# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &ci_toolkit
      automattic/a8c-ci-toolkit#3.0.1

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [*ci_toolkit]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Static code analysis"
    command: |
      echo "--- 🧹 Linting"
      ./gradlew ktlintcheck detekt
    plugins: [*ci_toolkit]
    artifact_paths:
      - "**/build/reports/ktlint/*"
      - "**/build/reports/detekt/detekt.html"

  - label: "Build"
    command: |
      echo "--- ⚒️ Building"
      ./gradlew assemble
    plugins: [*ci_toolkit]

  - label: "Unit tests"
    command: |
      echo "--- 🧪 Testing"
      ./gradlew test
    plugins: [*ci_toolkit]
    artifact_paths:
      - "**/build/test-results/*/*.xml"

  - wait: ~
    if: build.branch == "trunk" || build.tag != null

  - group: 🚀 Publish to S3
    key: publish-to-s3
    steps:
      - label: "🚀 Publish :gravatar"
        command: | 
          ./gradlew \
          :gravatar:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
          :gravatar:publish
        plugins: [*ci_toolkit]
        notify:
          - github_commit_status:
              context: "Publish :gravatar"
