agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Static code analysis"
    command: |
      echo "--- 🧹 Linting"
      ./gradlew ktlintcheck detekt

  - label: "Build"
    command: |
      echo "--- ⚒️ Building"
      ./gradlew assemble

  - label: "Unit tests"
    command: |
      echo "--- 🧪 Testing"
      ./gradlew test
    artifact_paths:
      - "**/build/test-results/*/*.xml"
